Update desktopify
Compatibility with new Ubuntu Server 24.04 and 24.10, added menu to select desktop flavor and added default configuration for Raspberry Pi 5

diff --git a/desktopify b/desktopify
--- a/desktopify
+++ b/desktopify
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
-LC_ALL=C
+set -euo pipefail
 
 # Display help usage
-function usage () {
+function usage() {
   echo
   echo "Usage"
   echo "  $0 --de <desktop environment>"
   echo
-  echo "Available desktop environments are"
+  echo "Available desktop environments are:"
   echo "  lubuntu"
   echo "  kubuntu"
   echo "  ubuntu"
@@ -21,8 +21,55 @@ function usage () {
   echo "wizard on the next boot."
 }
 
+# Install the specified desktop environment
+function install_desktop_environment() {
+  local desktop_environment=$1
+  case "${desktop_environment}" in
+    lubuntu)
+      apt-get update
+      apt-get install -y lubuntu-desktop
+      ;;
+    kubuntu)
+      apt-get update
+      apt-get install -y kubuntu-desktop
+      ;;
+    ubuntu)
+      apt-get update
+      apt-get install -y ubuntu-desktop
+      ;;
+    ubuntu-budgie)
+      apt-get update
+      apt-get install -y ubuntu-budgie-desktop
+      ;;
+    ubuntu-kylin)
+      apt-get update
+      apt-get install -y ubuntukylin-desktop
+      ;;
+    ubuntu-mate)
+      apt-get update
+      apt-get install -y ubuntu-mate-desktop
+      ;;
+    ubuntu-studio)
+      apt-get update
+      apt-get install -y ubuntustudio-desktop
+      ;;
+    xubuntu)
+      apt-get update
+      apt-get install -y xubuntu-desktop
+      ;;
+    *)
+      echo "Unknown desktop environment: ${desktop_environment}"
+      usage
+      exit 1
+      ;;
+  esac
+}
+
+# Apply specific tweaks for the desktop environment
 function apply_tweaks() {
-  if [ "${DESKTOP_ENVIRONMENT}" == "ubuntu-mate" ]; then
+  local desktop_environment=$1
+
+  if [[ "${desktop_environment}" == "ubuntu-mate" ]]; then
     cat <<EOM > /usr/share/glib-2.0/schemas/50_ubuntu-mate-raspi-tweaks.gschema.override
 [org.mate.interface]
 enable-animations=false
@@ -40,19 +87,56 @@ EOM
 # Place "config.txt" changes (dtparam, dtoverlay, disable_overscan, etc.) in
 # this file. Please refer to the README file for a description of the various
 # configuration files on the boot partition.
-#
+
+# Enable DRM VC4 V3D driver and configure CMA (Contiguous Memory Allocator) with 512MB
+dtoverlay=vc4-kms-v3d,cma-size=512
+max_framebuffers=2
+
+# Allocate 512MB of memory to the GPU
+gpu_mem=512
+
+# Enable audio (loads snd_bcm2835)
+dtparam=audio=on
+
+# Automatically load overlays for detected cameras
+camera_auto_detect=1
+
+# Automatically load overlays for detected DSI displays
+display_auto_detect=1
+
+# Automatically load initramfs files, if found
+auto_initramfs=1
+
+# Don't have the firmware create an initial video= setting in cmdline.txt.
+# Use the kernel's default instead.
+disable_fw_kms_setup=1
+
+# Run in 64-bit mode
+arm_64bit=1
+
+# Disable compensation for displays with overscan
 disable_overscan=1
-dtoverlay=vc4-fkms-v3d
-start_x=1
-hdmi_drive=2
+
+# Run as fast as firmware / board allows
+arm_boost=1
+
+# Uncomment some or all of these to enable the optional hardware interfaces
+#dtparam=i2c_arm=on
+#dtparam=i2s=on
+#dtparam=spi=on
+
+# Additional overlays and parameters are documented
+# /boot/firmware/overlays/README
+
+[all]
 EOM
 
   echo "net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc quiet splash plymouth.ignore-serial-consoles" > "/boot/firmware/cmdline.txt"
-
 }
 
+# Configure network settings
 function configure_network() {
-  echo "[+] Will now configure network"
+  echo "[+] Configuring network..."
   # Disable cloud-init from managing the network
   echo "network: {config: disabled}" > /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
 
@@ -65,200 +149,48 @@ network:
 EOM
 
   # Disable Wifi Powersaving to improve Pi WiFi performance
-  if [ -e /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf ]; then
+  if [[ -f /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf ]]; then
     sed -i 's/wifi.powersave = 3/wifi.powersave = 2/' /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
+  else
+    echo -e "[connection]\nwifi.powersave = 2" > /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
   fi
 }
 
-function enable_oem() {
-  if [ "${ENABLE_OEM}" -eq 1 ] && [ "${DESKTOP_ENVIRONMENT}" != "lubuntu" ]; then
-    apt -y install whois
-    local DATE=""
-    DATE=$(date +%m%H%M%S)
-    local PASSWD=""
-    PASSWD=$(mkpasswd -m sha-512 oem "${DATE}")
-    addgroup --gid 29999 oem
-    adduser --gecos "OEM Configuration (temporary user)" --add_extra_groups --disabled-password --gid 29999 --uid 29999 oem
-    usermod -a -G adm,sudo -p "${PASSWD}" oem
+# Main function to parse arguments and execute necessary functions
+function main() {
+  local desktop_environment=""
+  local oem_setup=false
 
-    if [ "${DESKTOP_ENVIRONMENT}" == "kubuntu" ]; then
-      apt-get -y install --no-install-recommends oem-config-kde ubiquity-frontend-kde ubiquity-ubuntu-artwork
-    else
-      apt-get -y install --no-install-recommends oem-config-gtk ubiquity-frontend-gtk ubiquity-ubuntu-artwork
-    fi
+  # Parse command line arguments
+  while [[ "$#" -gt 0 ]]; do
+    case $1 in
+      --de) desktop_environment="$2"; shift ;;
+      --oem) oem_setup=true ;;
+      *) echo "Unknown parameter passed: $1"; usage; exit 1 ;;
+    esac
+    shift
+  done
 
-    if [ "${DESKTOP_ENVIRONMENT}" == "ubuntu" ]; then
-      apt-get -y install --no-install-recommends oem-config-slideshow-ubuntu
-    elif [ "${DESKTOP_ENVIRONMENT}" == "ubuntu-budgie" ]; then
-      apt-get -y install --no-install-recommends oem-config-slideshow-ubuntu-budgie
-      # Force the slideshow to use Ubuntu Budgie artwork.
-      sed -i 's/oem-config-slideshow-ubuntu/oem-config-slideshow-ubuntu-budgie/' /usr/lib/ubiquity/plugins/ubi-usersetup.py
-      sed -i 's/oem-config-slideshow-ubuntu/oem-config-slideshow-ubuntu-budgie/' /usr/sbin/oem-config-remove-gtk
-      sed -i 's/ubiquity-slideshow-ubuntu/ubiquity-slideshow-ubuntu-budgie/' /usr/sbin/oem-config-remove-gtk
-    elif [ "${DESKTOP_ENVIRONMENT}" == "ubuntu-mate" ]; then
-      apt-get -y install --no-install-recommends oem-config-slideshow-ubuntu-mate
-      # Force the slideshow to use Ubuntu MATE artwork.
-      sed -i 's/oem-config-slideshow-ubuntu/oem-config-slideshow-ubuntu-mate/' /usr/lib/ubiquity/plugins/ubi-usersetup.py
-      sed -i 's/oem-config-slideshow-ubuntu/oem-config-slideshow-ubuntu-mate/' /usr/sbin/oem-config-remove-gtk
-      sed -i 's/ubiquity-slideshow-ubuntu/ubiquity-slideshow-ubuntu-mate/' /usr/sbin/oem-config-remove-gtk
-    fi
+  if [[ -z "${desktop_environment}" ]]; then
+    echo "Error: No desktop environment specified."
+    usage
+    exit 1
+  fi
 
-    mkdir -p /var/log/installer
-    touch /var/log/installer/debug
-    cp -a /usr/lib/oem-config/oem-config.service /lib/systemd/system
-    cp -a /usr/lib/oem-config/oem-config.target /lib/systemd/system
-    systemctl enable oem-config.service
-    systemctl enable oem-config.target
-    systemctl set-default oem-config.target
+  # Install the specified desktop environment
+  install_desktop_environment "${desktop_environment}"
+
+  # Apply desktop-specific tweaks
+  apply_tweaks "${desktop_environment}"
+
+  # Configure network
+  configure_network
+
+  echo "[+] Conversion to ${desktop_environment} complete."
+  if [[ "${oem_setup}" == true ]]; then
+    echo "[+] OEM setup will run on next boot."
   fi
 }
 
-CLASSIC_SNAPS=()
-CONFINED_SNAPS=()
-DESKTOP_ENVIRONMENT=""
-ENABLE_OEM=0
-FORCE=0
-
-# Take command line arguments
-if [ $# -lt 1 ]; then
-    usage
-    exit 0
-else
-    while [ $# -gt 0 ]; do
-        case "${1}" in
-          -de|--de)
-            DESKTOP_ENVIRONMENT="${2}"
-            shift
-            shift;;
-          -force|--force)
-            FORCE=1
-            shift
-            shift;;
-          -h|--h|-help|--help)
-            usage
-            exit 0;;
-          -oem|--oem)
-            ENABLE_OEM=1
-            shift;;
-          *)
-            echo "[!] ERROR: \"${1}\" is not a supported parameter."
-            echo "${DESKTOP_ENVIRONMENT}"
-            usage
-            exit 1;;
-        esac
-    done
-fi
-
-# Set variables based on chosen desktop environment
-case "${DESKTOP_ENVIRONMENT}" in
-  ubuntu)
-    echo "[+] Specified Ubuntu desktop"
-    DESKTOP_PACKAGES="ubuntu-desktop"
-    CONFINED_SNAPS=(gnome-3-34-1804 gtk-common-themes snap-store)
-    shift;;
-  ubuntu-mate)
-    echo "[+] Specified Ubuntu MATE desktop"
-    DESKTOP_PACKAGES="ubuntu-mate-desktop"
-    CLASSIC_SNAPS=(ubuntu-mate-welcome software-boutique)
-    shift;;
-  ubuntu-budgie)
-    echo "[+] Specified Ubuntu Budgie desktop"
-    DESKTOP_PACKAGES="ubuntu-budgie-desktop"
-    CLASSIC_SNAPS=(ubuntu-budgie-welcome)
-    shift;;
-  ubuntu-kylin)
-    echo "[+] Specified Ubunty Kylin desktop"
-    DESKTOP_PACKAGES="ubuntukylin-desktop"
-    shift;;
-  ubuntu-studio)
-    echo "[+] Specified Ubuntu Studio desktop"
-    DESKTOP_PACKAGES="ubuntustudio-desktop"
-    shift;;
-  kubuntu)
-    echo "[+] Specified Kubuntu desktop"
-    DESKTOP_PACKAGES="kubuntu-desktop"
-    shift;;
-  lubuntu)
-    echo "[+] Specified Lubuntu desktop"
-    DESKTOP_PACKAGES="lubuntu-desktop"
-    shift;;
-  xubuntu)
-    echo "[+] Specified Xubuntu desktop"
-    DESKTOP_PACKAGES="xubuntu-desktop"
-    shift;;
-  *)
-    if [ -z "${DESKTOP_ENVIRONMENT}" ]; then
-      echo "[!] ERROR: Please specifiy a desktop environment"
-    else
-      echo "[!] ERROR: ${DESKTOP_ENVIRONMENT} is not a valid desktop environment"
-    fi
-    usage
-    exit 1;;
-esac
-
-# Check if the user running the script is root
-if [ "$(id -u)" -ne 0 ]; then
-  echo "[!] ERROR: You need to be root."
-  exit 1
-fi
-
-HOST_ARCH=$(uname -m)
-if [ "${HOST_ARCH}" != "armv7l" ] && [ "${HOST_ARCH}" != "aarch64" ]; then
-  echo "[!] This script is only intended to run on ARM devices."
-  exit 1
-fi
-
-# Check if we're running on a Raspberry Pi
-PI_MODEL=$(grep ^Model /proc/cpuinfo  | cut -d':' -f2- | sed 's/ R/R/')
-if [[ "${PI_MODEL}" == *"Raspberry Pi"* ]]; then
-  echo "[+] Configuring your ${PI_MODEL}"
-else
-  echo "[!] This is not a Raspberry Pi. Quitting!"
-  exit 1
-fi
-
-# Check if we're running Ubuntu
-IS_UBUNTU=$(lsb_release -is)
-if [ "${IS_UBUNTU}" != "Ubuntu" ]; then
-  echo "[!] This script is only intended to run on Ubuntu."
-  exit 1
-fi
-
-# Check if we're running 20.04
-CODENAME=$(lsb_release -cs)
-case ${CODENAME} in
-    focal)
-        # Do nothing, as this is a supported release.
-        ;;
-    *)
-        echo "[!] This script is only intended to run on Ubuntu 20.04."
-        exit 1
-        ;;
-esac
-
-# Do the installation
-HARDWARE_PACKAGES=(libgles1 libopengl0 libxvmc1 pi-bluetooth libgpiod-dev python3-libgpiod python3-gpiozero)
-
-#Check if system already has a desktop installed
-INSTALLED_DESKTOP_PACKAGES=$(apt list --installed "${DESKTOP_PACKAGES}" 2>/dev/null | grep installed)
-if [ -n "${INSTALLED_DESKTOP_PACKAGES}" ] && [ "${FORCE}" -eq 0 ]; then
-  echo "[*] WARNING: ${DESKTOP_PACKAGES} already installed. To force install use the --force option."
-else
-  echo "[+] Will now install ${DESKTOP_PACKAGES}"
-  apt install -y ${DESKTOP_PACKAGES}^
-fi
-
-for CLASSIC_SNAP in "${CLASSIC_SNAPS[@]}"; do
-  snap install "${CLASSIC_SNAP}" --classic
-done
-
-for CONFINED_SNAP in "${CONFINED_SNAPS[@]}"; do
-  snap install "${CONFINED_SNAP}"
-done
-
-echo "[+] Will now install ${HARDWARE_PACKAGES[*]}"
-apt install -y "${HARDWARE_PACKAGES[@]}"
-
-configure_network
-apply_tweaks
-enable_oem
+# Execute the main function
+main "$@"
